In [88]:
"""

LICENSE MIT
2020
Guillaume Rozier
Website : http://www.covidtracker.fr
Mail : guillaume.rozier@telecomnancy.net

README:
This file contains scripts that download data from data.gouv.fr and then process it to build many graphes.
I'm currently cleaning the code, please ask me if something is not clear enough.

The charts are exported to 'charts/images/france'.
Data is download to/imported from 'data/france'.
Requirements: please see the imports below (use pip3 to install them).

"""

"\n\nLICENSE MIT\n2020\nGuillaume Rozier\nWebsite : http://www.covidtracker.fr\nMail : guillaume.rozier@telecomnancy.net\n\nREADME:\nThis file contains scripts that download data from data.gouv.fr and then process it to build many graphes.\nI'm currently cleaning the code, please ask me if something is not clear enough.\n\nThe charts are exported to 'charts/images/france'.\nData is download to/imported from 'data/france'.\nRequirements: please see the imports below (use pip3 to install them).\n\n"

In [89]:
def nbWithSpaces(nb):
    str_nb = str(int(round(nb)))
    if(nb>100000):
        return str_nb[:3] + " " + str_nb[3:]
    elif(nb>10000):
        return str_nb[:2] + " " + str_nb[2:]
    elif(nb>1000):
        return str_nb[:1] + " " + str_nb[1:]
    else:
        return str_nb

In [107]:
import pandas as pd
PATH = "../../"
import france_data_management as data
import plotly.graph_objects as go
import locale
from datetime import datetime
locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
now = datetime.now()

In [91]:
data.download_data()
df_tests =data.import_data_tests_sexe()
df_tests = df_tests[df_tests.cl_age90 == 0]
df_tests["P_rolling"] = df_tests["P"].rolling(window=7).mean()
df_tests

36it [00:04,  7.22it/s]

,fra,jour,P_f,P_h,P,T_f,T_h,T,cl_age90,pop,P_rolling
10,FR,2020-05-13,537,361,901,23368,16324,39872,0,67114995.0,NaN
21,FR,2020-05-14,561,418,1013,25327,17616,43188,0,67114995.0,NaN
32,FR,2020-05-15,565,447,1046,27514,20518,48470,0,67114995.0,NaN
43,FR,2020-05-16,160,131,292,9232,7342,16674,0,67114995.0,NaN
54,FR,2020-05-17,78,62,140,3446,3162,6642,0,67114995.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3233,FR,2021-03-02,12911,11469,24540,188026,152129,341109,0,67114995.0,21072.285714
3244,FR,2021-03-03,12159,11230,23523,174937,148219,324126,0,67114995.0,20972.000000
3255,FR,2021-03-04,12313,11128,23572,187246,160184,348518,0,67114995.0,20883.428571
3266,FR,2021-03-05,13028,11909,25089,212262,184553,398659,0,67114995.0,20898.142857
3277,FR,2021-03-06,7887,7314,15263,111029,101189,212803,0,67114995.0,21012.285714

In [92]:
data.download_data_variants()
df_variants = data.import_data_variants()
df_variants

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS
0,FR,2021-02-12-2021-02-18,9,3554,56.1,1890,53.2,143,4.0,376,10.6,1145,32.2
1,FR,2021-02-12-2021-02-18,19,10488,53.2,5326,50.8,498,4.7,870,8.3,3794,36.2
2,FR,2021-02-12-2021-02-18,29,11640,49.2,5661,48.6,592,5.1,969,8.3,4418,38.0
3,FR,2021-02-12-2021-02-18,39,12256,50.4,6242,50.9,549,4.5,982,8.0,4483,36.6
4,FR,2021-02-12-2021-02-18,49,12379,52.0,6210,50.2,508,4.1,965,7.8,4696,37.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,FR,2021-02-24-2021-03-02,0,102975,59.5,62432,60.6,5499,5.3,8453,8.2,26591,25.8
183,FR,2021-02-25-2021-03-03,0,101971,59.1,63334,62.1,5332,5.2,8436,8.3,24869,24.4
184,FR,2021-02-26-2021-03-04,0,99910,58.2,63430,63.5,5188,5.2,8262,8.3,23030,23.1
185,FR,2021-02-27-2021-03-05,0,95039,55.5,61401,64.6,4780,5.0,8034,8.5,20824,21.9
186,FR,2021-02-28-2021-03-06,0,91856,53.4,59951,65.3,4555,5.0,7807,8.5,19543,21.3

In [93]:
df_variants["jour"] = df_variants.semaine.apply(lambda x: x[11:]) 
df_variants = df_variants[df_variants.cl_age90==0]
df_variants

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS,jour
170,FR,2021-02-12-2021-02-18,0,81274,51.9,37940,46.7,3496,4.3,6988,8.6,32850,40.4,2021-02-18
171,FR,2021-02-13-2021-02-19,0,88569,55.1,41245,46.6,3987,4.5,7786,8.8,35551,40.1,2021-02-19
172,FR,2021-02-14-2021-02-20,0,91552,56.2,42935,46.9,4251,4.6,7953,8.7,36413,39.8,2021-02-20
173,FR,2021-02-15-2021-02-21,0,92272,56.4,43402,47.0,4273,4.6,8068,8.7,36529,39.6,2021-02-21
174,FR,2021-02-16-2021-02-22,0,96420,57.2,47408,49.2,4452,4.6,8483,8.8,36077,37.4,2021-02-22
175,FR,2021-02-17-2021-02-23,0,99643,58.0,50687,50.9,4821,4.8,8772,8.8,35363,35.5,2021-02-23
176,FR,2021-02-18-2021-02-24,0,101708,58.5,53593,52.7,4997,4.9,8716,8.6,34402,33.8,2021-02-24
177,FR,2021-02-19-2021-02-25,0,103068,58.9,55917,54.3,5124,5.0,8868,8.6,33159,32.2,2021-02-25
178,FR,2021-02-20-2021-02-26,0,103575,59.2,57869,55.9,5437,5.2,8682,8.4,31587,30.5,2021-02-26
179,FR,2021-02-21-2021-02-27,0,103881,59.3,58756,56.6,5590,5.4,8704,8.4,30831,29.7,2021-02-27
180,FR,2021-02-22-2021-02-28,0,103927,59.3,58918,56.7,5611,5.4,8676,8.3,30722,29.6,2021-02-28
181,FR,2021-02-23-2021-03-01,0,103736,59.7,61135,58.9,5697,5.5,8507,8.2,28397,27.4,2021-03-01
182,FR,2021-02-24-2021-03-02,0,102975,59.5,62432,60.6,5499,5.3,8453,8.2,26591,25.8,2021-03-02
183,FR,2021-02-25-2021-03-03,0,101971,59.1,63334,62.1,5332,5.2,8436,8.3,24869,24.4,2021-03-03
184,FR,2021-02-26-2021-03-04,0,99910,58.2,63430,63.5,5188,5.2,8262,8.3,23030,23.1,2021-03-04
185,FR,2021-02-27-2021-03-05,0,95039,55.5,61401,64.6,4780,5.0,8034,8.5,20824,21.9,2021-03-05
186,FR,2021-02-28-2021-03-06,0,91856,53.4,59951,65.3,4555,5.0,7807,8.5,19543,21.3,2021-03-06

In [94]:
df_variants.Nb_tests_PCR_TA_crible / (df_variants.Prc_tests_PCR_TA_crible/100)

170    156597.302505
171    160742.286751
172    162903.914591
173    163602.836879
174    168566.433566
175    171798.275862
176    173859.829060
177    174988.115450
178    174957.770270
179    175178.752108
180    175256.323777
181    173762.144054
182    173067.226891
183    172539.763113
184    171666.666667
185    171241.441441
186    172014.981273
dtype: float64

In [108]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V1,
        name="% variant UK (" + str(df_variants.Prc_susp_501Y_V1.values[-1]).replace(".", ",") + " %)",
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_ABS,
        name="% souche classique (" + str(df_variants.Prc_susp_ABS.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_IND,
        name="% variants indéterminés (" + str(df_variants.Prc_susp_IND.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V2_3,
        name="% variants SA + BZ (" + str(df_variants.Prc_susp_501Y_V2_3.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
    )
)

fig.update_yaxes(ticksuffix="%")

fig.update_layout(
     title={
        'text': "Proportion de variants dans les tests positifs (en %)",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour le {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_pourcent"), scale=2, width=1000, height=600)

In [113]:
fig = go.Figure()
n_days = len(df_variants)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V2_3.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variants SA + BZ </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_501Y_V2_3.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_IND.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variants indéterminés </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_IND.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_ABS.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Souche classique </b><br>" + str(nbWithSpaces(y[-1])) + " (" + str(df_variants.Prc_susp_ABS.values[-1]).replace(".", ",") + " %) ",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variant UK </b><br>" + str(nbWithSpaces(y[-1])).replace(".", ",") + " (" + str(df_variants.Prc_susp_501Y_V1.values[-1]).replace(".", ",") + " %) ",
        stackgroup='one'
    )
)

fig.update_yaxes(ticksuffix="")

fig.update_layout(
     title={
        'text': "Nombre de variants dans les cas détectés",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Mis à jour : {}. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.'.format(now.strftime('%d %B')),
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_nombre"), scale=2, width=1000, height=600)