In [113]:
"""
LICENSE MIT
2021
Guillaume Rozier
Website : http://www.covidtracker.fr
Mail : guillaume.rozier@telecomnancy.net

README:
This file contains scripts that download data from data.gouv.fr and then process it to build many graphes.
I'm currently cleaning the code, please ask me if something is not clear enough.

The charts are exported to 'charts/images/france'.
Data is download to/imported from 'data/france'.
Requirements: please see the imports below (use pip3 to install them).

"""

"\nLICENSE MIT\n2021\nGuillaume Rozier\nWebsite : http://www.covidtracker.fr\nMail : guillaume.rozier@telecomnancy.net\n\nREADME:\nThis file contains scripts that download data from data.gouv.fr and then process it to build many graphes.\nI'm currently cleaning the code, please ask me if something is not clear enough.\n\nThe charts are exported to 'charts/images/france'.\nData is download to/imported from 'data/france'.\nRequirements: please see the imports below (use pip3 to install them).\n\n"

In [114]:
import pandas as pd
import json
import france_data_management as data
import math

show_charts = False
PATH_STATS = "../../data/france/stats/"

In [115]:
df, df_confirmed, dates, df_new, df_tests, df_deconf, df_sursaud, df_incid, df_tests_viros = data.import_data()

  0%|          | 0/8 [00:00<?, ?it/s]

 38%|███▊      | 3/8 [00:01<00:03,  1.60it/s]

 75%|███████▌  | 6/8 [00:03<00:01,  1.72it/s]

15it [00:03,  2.43it/s]

21it [00:15,  1.15it/s]

28it [03:14,  8.31s/it]

36it [03:14,  5.82s/it]

In [140]:
data.download_data_vue_ensemble()
df_vue_ensemble = data.import_data_vue_ensemble()

,date,total_cas_confirmes,total_deces_hopital,total_deces_ehpad,total_cas_confirmes_ehpad,total_cas_possibles_ehpad,patients_reanimation,patients_hospitalises,total_patients_gueris,nouveaux_patients_hospitalises,nouveaux_patients_reanimation
0,2020-03-02,191,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-03-03,212,4,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN
2,2020-03-04,285,4,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN
3,2020-03-05,423,7,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN
4,2020-03-06,613,9,NaN,NaN,NaN,39.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
353,2021-02-18,3536648,59159,24234.0,186226.0,NaN,3394.0,25762.0,247127.0,1486.0,261.0
354,2021-02-19,3560764,59484,24480.0,188270.0,NaN,3390.0,25551.0,248488.0,1537.0,308.0
355,2021-02-20,3583135,59641,24480.0,NaN,NaN,3369.0,25269.0,249520.0,1029.0,195.0
356,2021-02-21,3605181,59800,24480.0,NaN,NaN,3392.0,25464.0,249727.0,593.0,141.0
357,2021-02-22,3609827,60133,24480.0,NaN,NaN,3407.0,25831.0,250532.0,1529.0,274.0

In [168]:
df_metro = data.import_data_metropoles()
df_metro["jour"] = df_metro["semaine_glissante"].map(lambda x: x[11:])

df_metro_65 = df_metro[df_metro["clage_65"] == 65]
df_metro_0 = df_metro[df_metro["clage_65"] == 0]
metropoles = list(dict.fromkeys(list(df_metro['Metropole'].dropna().values))) 
df_metro_0

       epci2020      semaine_glissante  clage_65     ti Metropole        jour
0     200030195  2021-01-14-2021-01-20         0  494.5      Nice  2021-01-20
2     200030195  2021-01-15-2021-01-21         0  493.6      Nice  2021-01-21
4     200030195  2021-01-16-2021-01-22         0  497.0      Nice  2021-01-22
6     200030195  2021-01-17-2021-01-23         0  501.9      Nice  2021-01-23
8     200030195  2021-01-18-2021-01-24         0  507.9      Nice  2021-01-24
...         ...                    ...       ...    ...       ...         ...
1354  248300543  2021-02-09-2021-02-15         0  192.4    Toulon  2021-02-15
1356  248300543  2021-02-10-2021-02-16         0  186.1    Toulon  2021-02-16
1358  248300543  2021-02-11-2021-02-17         0  195.5    Toulon  2021-02-17
1360  248300543  2021-02-12-2021-02-18         0  196.2    Toulon  2021-02-18
1362  248300543  2021-02-13-2021-02-19         0  201.2    Toulon  2021-02-19

[682 rows x 6 columns]

In [116]:
df_tests_viros_enrichi = data.import_data_tests_viros()
df_tests_viros_enrichi = df_tests_viros_enrichi.drop("regionName_y", axis=1).rename({"regionName_x": "regionName"}, axis=1)

In [117]:
df_incid_clage = df_incid.copy()

df_incid_fra_clage = data.import_data_tests_sexe()
df_incid_fra = df_incid_fra_clage[df_incid_fra_clage["cl_age90"]==0]
df_france = df.groupby(["jour"]).sum().reset_index()
df_incid = df_incid[df_incid.cl_age90 == 0]

df_sursaud_france = df_sursaud.groupby(["date_de_passage"]).sum().reset_index()
df_sursaud_regions = df_sursaud.groupby(["date_de_passage", "regionName"]).sum().reset_index()

df_new_france = df_new.groupby(["jour"]).sum().reset_index()
df_new_regions = df_new.groupby(["jour", "regionName"]).sum().reset_index()

In [118]:
df_incid_clage_regions = df_incid_clage.groupby(["regionName", "jour", "cl_age90"]).sum().reset_index()

In [119]:
df_tests_viros_regions = df_tests_viros_enrichi.groupby(["regionName", "jour", "cl_age90"]).sum().reset_index()
df_tests_viros_france = df_tests_viros_enrichi.groupby(["jour", "cl_age90"]).sum().reset_index()

In [120]:
df_hosp_clage = data.import_data_hosp_clage()
df_hosp_clage_france = df_hosp_clage.groupby(["jour", "cl_age90"]).sum().reset_index()
df_hosp_clage_regions = df_hosp_clage.groupby(["regionName", "jour", "cl_age90"]).sum().reset_index()

In [121]:
departements = list(dict.fromkeys(list(df_incid['dep'].values))) 
regions = list(dict.fromkeys(list(df_incid['regionName'].dropna().values))) 
clage_list = list(dict.fromkeys(list(df_incid_fra_clage['cl_age90'].dropna().values))) 

df_regions = df.groupby(["jour", "regionName"]).sum().reset_index()
df_incid_regions = df_incid.groupby(["jour", "regionName"]).sum().reset_index()


zone_a = ["zone_a", "01", "03", "07", "15", "16", "17", "19", "21", "23", "24", "25", "26", "33", "38", "39", "40", "42", "43", "47", "58", "63", "64", "69", "70", "71", "73", "74", "79", "86", "90"]
zone_b = ["zone_b", "02", "04", "05", "06", "08", "10", "13", "14", "18", "22", "27", "28", "29", "35", "36", "37", "41", "44", "45", "49", "50", "51", "52", "53", "54", "55", "56", "57", "59", "60", "61", "62", "67", "68", "72", "76", "80", "83", "84", "85", "88"]
zone_c = ["zone_c", "09", "11", "12", "30", "31", "32", "34", "46", "48", "65", "66", "75", "77", "78", "81", "82", "91", "92", "93", "94", "95"]

In [188]:
def generate_data(data_incid=pd.DataFrame(), data_hosp=pd.DataFrame(), data_sursaud=pd.DataFrame(), data_new=pd.DataFrame(), data_vue_ensemble=pd.DataFrame(), data_metropole=pd.DataFrame(), mode="", export_jour=False):## Incidence
        
    dict_data = {}
    
    if export_jour:
        dict_data["jour_incid"] = list(data_incid.jour)
        dict_data["jour_hosp"] = list(data_hosp.jour)
        dict_data["jour_new"] = list(data_new.jour)
        dict_data["jour_sursaud"] = list(data_sursaud.date_de_passage)
        dict_data["jour_metropoles"] = list(data_metropole.jour.unique())
    
    if len(data_vue_ensemble)>0:
        dict_data["jour_ehpad"] = list(data_vue_ensemble.date)
        deces_ehpad = data_vue_ensemble["total_deces_ehpad"].diff().rolling(window=7).mean().fillna(0)
        dict_data["deces_ehpad"] = {"jour_nom": "jour_ehpad", "valeur": list(round(deces_ehpad,2))}
        
    if len(data_incid)>0:
        taux_incidence = data_incid["P"].rolling(window=7).sum().fillna(0) * 100000 / data_incid["pop"].values[0]
        dict_data["incidence"] = {"jour_nom": "jour_incid", "valeur": list(round(taux_incidence,2))}

        taux_positivite = (data_incid["P"].rolling(window=7).sum() * 100 / data_incid["T"].rolling(window=7).sum()).fillna(0)
        dict_data["taux_positivite"] = {"jour_nom": "jour_incid", "valeur": list(round(taux_positivite,2))}
    
        cas = data_incid["P"].rolling(window=7).mean().fillna(0)
        dict_data["cas"] = {"jour_nom": "jour_incid", "valeur": list(round(cas,2))}
    
        tests = data_incid["T"].rolling(window=7).mean().fillna(0)
        dict_data["tests"] = {"jour_nom": "jour_incid", "valeur": list(round(tests,2))}
        
    if (len(data_metropole)>0) & (mode=="metropoles"):
        taux_incidence = data_metropole["ti"].fillna(0)
        dict_data["incidence"] = {"jour_nom": "jour_metropoles", "valeur": list(round(taux_incidence, 2))}
        
    if len(data_hosp)>0:
        hospitalisations = data_hosp.hosp.fillna(0)
        dict_data["hospitalisations"] = {"jour_nom": "jour_hosp", "valeur": list(hospitalisations)}

        reanimations = data_hosp.rea.fillna(0)
        dict_data["reanimations"] = {"jour_nom": "jour_hosp", "valeur": list(reanimations)}
    
    if len(data_new)>0:
        incid_hospitalisations = data_new.incid_hosp.rolling(window=7).mean().fillna(0)
        dict_data["incid_hospitalisations"] = {"jour_nom": "jour_new", "valeur": list(round(incid_hospitalisations, 2))}

        incid_reanimations = data_new.incid_rea.rolling(window=7).mean().fillna(0)
        dict_data["incid_reanimations"] = {"jour_nom": "jour_new", "valeur": list(round(incid_reanimations,2))}
    
    if len(data_sursaud)>0:
        nbre_acte_corona = data_sursaud.nbre_acte_corona.rolling(window=7).mean().fillna(0)
        dict_data["nbre_acte_corona"] = {"jour_nom": "jour_sursaud", "valeur": list(round(nbre_acte_corona, 2))}

        nbre_pass_corona = data_sursaud.nbre_pass_corona.rolling(window=7).mean().fillna(0)
        dict_data["nbre_pass_corona"] = {"jour_nom": "jour_sursaud", "valeur": list(round(nbre_pass_corona, 2))}
    
    if len(data_hosp)>0:
        deces_hospitaliers = data_hosp.dc.diff().rolling(window=7).mean().fillna(0)
        dict_data["deces_hospitaliers"] = {"jour_nom": "jour_hosp", "valeur": list(round(deces_hospitaliers,2))}
    
    if len(data_incid)>0:
        population = data_incid["pop"].values[0]
        dict_data["population"] = population

    return dict_data

In [123]:
def generate_data_age(data_incid, data_hosp, export_jour=False):## Incidence
    clage_tranches = [[0], [9, 19], [29, 39], [49, 59], [69, 79], [89, 90]]
    clage_noms = ["tous", "19", "39", "59", "79", "90"]
    clage_noms_disp = ["Tous âges", "0 à 19 ans", "20 à 39 ans", "40 à 59 ans", "60 à 79 ans", "Plus de 80 ans"]
    
    dict_data = {}
    
    for (idx, clage) in enumerate(clage_tranches):
        clage_nom = clage_noms[idx]
        
        data_incid_clage = data_incid[data_incid.cl_age90.isin(clage)].groupby("jour").sum().reset_index()

        dict_data[clage_nom] = {}

        taux_incidence = data_incid_clage["P"].rolling(window=7).sum().fillna(0) * 100000 / data_incid_clage["pop"].values[0]
        dict_data[clage_nom]["incidence"] = {"jour_nom": "jour_incid", "valeur": list(round(taux_incidence,2))}

        taux_positivite = (data_incid_clage["P"].rolling(window=7).sum() * 100 / data_incid_clage["T"].rolling(window=7).sum()).fillna(0)
        dict_data[clage_nom]["taux_positivite"] = {"jour_nom": "jour_incid", "valeur": list(round(taux_positivite,2))}

        cas = data_incid_clage["P"].rolling(window=7).mean().fillna(0)
        dict_data[clage_nom]["cas"] = {"jour_nom": "jour_incid", "valeur": list(round(cas,2))}

        tests = data_incid_clage["T"].rolling(window=7).mean().fillna(0)
        dict_data[clage_nom]["tests"] = {"jour_nom": "jour_incid", "valeur": list(round(tests,2))}
        
        population = data_incid_clage["pop"].values[0]
        dict_data[clage_nom]["population"] = population
        
        if (len(data_hosp)):
            
            data_hosp_clage = data_hosp[data_hosp.cl_age90.isin(clage)].groupby("jour").sum().reset_index()
            hospitalisations = data_hosp_clage.hosp.fillna(0)
            dict_data[clage_nom]["hospitalisations"] = {"jour_nom": "jour_hosp", "valeur": list(hospitalisations)}

            reanimations = data_hosp_clage.rea.fillna(0)
            dict_data[clage_nom]["reanimations"] = {"jour_nom": "jour_hosp", "valeur": list(reanimations)}

            deces_hospitaliers = data_hosp_clage.dc.diff().rolling(window=7).mean().fillna(0)
            dict_data[clage_nom]["deces_hospitaliers"] = {"jour_nom": "jour_hosp", "valeur": list(round(deces_hospitaliers,2))}
        
    if export_jour:
            dict_data["jour_incid"] = list(data_incid.jour.unique())
            dict_data["jour_hosp"] = list(data_hosp.jour.unique())
            dict_data["tranches"] = clage_tranches
            dict_data["tranches_noms"] = clage_noms
            dict_data["tranches_noms_affichage"] = clage_noms_disp

    return dict_data

In [142]:
def export_data(data, suffix=""):
    with open(PATH_STATS + 'dataexplorer{}.json'.format(suffix), 'w') as outfile:
        json.dump(data, outfile)

In [186]:
def dataexplorer():
    dict_data = {}
    
    dict_data["regions"] = sorted(regions)
    dict_data["metropoles"] = sorted(metropoles)
    dict_data["departements"] = departements
    dict_data["france"] = generate_data(df_incid_fra, df_france, df_sursaud_france, df_new_france, df_vue_ensemble, data_metropole=df_metro_0, mode="france", export_jour=True)
    
    noms_departements={}
    
    for reg in regions:
        
        dict_data[reg] = generate_data(df_incid_regions[df_incid_regions.regionName==reg], \
                                       df_regions[df_regions.regionName==reg],\
                                       df_sursaud_regions[df_sursaud_regions.regionName==reg],
                                       df_new_regions[df_new_regions.regionName==reg])
    
    for dep in departements:
        df_incid_dep = df_incid[df_incid.dep==dep]
        dict_data[dep] = generate_data(df_incid_dep, df[df.dep==dep], df_sursaud[df_sursaud.dep==dep], df_new[df_new.dep==dep])
        
        noms_departements[dep] = df_incid_dep["departmentName"].values[0]
    dict_data["departements_noms"] = noms_departements
    
    for zone in [zone_a, zone_b, zone_c]:
        df_incid_zone = df_incid[df_incid.dep.isin(zone)].groupby("jour").sum().reset_index()
        df_zone = df[df.dep.isin(zone)].groupby("jour").sum().reset_index()
        df_sursaud_zone = df_sursaud[df_sursaud.dep.isin(zone)].groupby("date_de_passage").sum().reset_index()
        df_new_zone = df_new[df_new.dep.isin(zone)].groupby("jour").sum().reset_index()
        
        dict_data[zone[0]] = generate_data(df_incid_zone, df_zone, df_sursaud_zone, df_new_zone)
        
    for metropole in metropoles:
        print(metropole)
        dict_data[metropole] = generate_data(data_metropole=df_metro_0[df_metro_0.Metropole == metropole], mode="metropoles")
        print(dict_data[metropole])
        
    dict_data["zones_vacances"] = ["zone_a", "zone_b", "zone_c"]
    
    export_data(dict_data, suffix="_compr")

In [146]:
import math
def dataexplorer_age():
    dict_data = {}
    regions_tests_viros = list(dict.fromkeys(list(df_tests_viros_enrichi['regionName'].dropna().values))) 
    departements_tests_viros = list(dict.fromkeys(list(df_tests_viros_enrichi['dep'].dropna().values))) 
    dict_data["regions"] = sorted(regions_tests_viros)
    dict_data["departements"] = sorted(departements_tests_viros)
    
    dict_data["france"] = generate_data_age(df_tests_viros_france, df_hosp_clage_france, export_jour=True)
    
    for reg in regions_tests_viros:
        dict_data[reg] = generate_data_age(df_tests_viros_regions[df_tests_viros_regions.regionName == reg],\
                                           df_hosp_clage_regions[df_hosp_clage_regions.regionName == reg])
    noms_departements={}
    for dep in departements_tests_viros:
        df_tests_viros_enrichi_temp = df_tests_viros_enrichi[df_tests_viros_enrichi.dep == dep]
        dict_data[dep] = generate_data_age(df_tests_viros_enrichi_temp,\
                                           pd.DataFrame())
        
        nom_dep = df_tests_viros_enrichi_temp["departmentName"].values[0]
        
        if(type(nom_dep) is float): #Pas de nom, nom_dep == NaN
            print(dep)
            nom_dep = "--"
        
        noms_departements[dep] = nom_dep
        
    dict_data["departements_noms"] = noms_departements
    
    export_data(dict_data, suffix="_compr_age")
    return dict_data

In [189]:
dataexplorer()

Nice
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [494.5, 493.6, 497.0, 501.9, 507.9, 507.7, 506.7, 510.5, 518.6, 526.8, 534.0, 530.3, 530.7, 535.3, 543.9, 544.3, 554.6, 552.0, 554.7, 570.8, 624.8, 678.8, 726.4, 737.9, 760.2, 760.4, 776.3, 762.8, 751.5, 753.3, 771.3]}}
Marseille
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [367.7, 380.2, 398.6, 402.6, 403.9, 407.5, 411.3, 409.9, 412.7, 408.0, 405.5, 405.0, 406.7, 412.1, 412.6, 410.1, 403.1, 403.0, 401.5, 391.5, 387.5, 381.4, 368.1, 363.5, 356.2, 353.5, 345.6, 335.4, 331.5, 334.7, 334.3]}}
Dijon
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [200.0, 199.8, 190.7, 188.7, 190.3, 187.7, 183.9, 184.1, 183.4, 185.3, 187.2, 187.2, 177.9, 179.0, 173.8, 167.5, 161.6, 159.2, 156.1, 152.7, 147.0, 149.2, 151.3, 152.8, 143.7, 142.5, 137.8, 127.7, 112.9, 106.8, 96.7]}}
Brest
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [49.1, 49.9, 54.1, 53.0, 58.3, 56.3, 53.4, 54.1, 60.9, 54.5, 52.1, 48.3, 49.0, 57.0, 52.2, 47.6, 49.7, 49.8, 49.4, 42.5, 37.9, 35.5, 32.5, 33.7, 32.3, 31.9, 31.5, 26.2, 31.9, 35.7, 34.8]}}
Toulouse
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [202.5, 206.3, 214.3, 211.0, 213.4, 221.6, 229.1, 232.8, 244.6, 245.3, 254.7, 264.2, 272.9, 273.3, 277.2, 277.7, 283.2, 277.4, 270.3, 254.7, 247.3, 240.6, 236.0, 230.9, 228.5, 224.8, 225.2, 219.0, 222.6, 219.9, 217.3]}}
Bordeaux
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [169.5, 170.6, 176.9, 173.1, 174.5, 180.5, 181.9, 180.5, 175.0, 176.1, 176.9, 177.2, 173.0, 170.0, 167.7, 163.5, 151.6, 148.3, 144.9, 129.5, 121.2, 121.7, 122.7, 123.1, 124.7, 127.0, 128.6, 131.2, 131.8, 131.1, 137.9]}}
Montpellier
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [145.3, 147.5, 147.4, 149.4, 147.8, 146.4, 139.6, 136.3, 135.7, 137.4, 135.7, 135.9, 133.2, 136.5, 140.2, 136.9, 133.1, 132.5, 131.7, 131.7, 127.4, 121.8, 120.4, 121.0, 117.5, 117.2, 113.2, 108.7, 105.4, 104.7, 105.5]}}
Rennes
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [161.4, 169.5, 163.0, 165.9, 165.4, 171.0, 163.9, 161.2, 166.8, 182.6, 182.9, 184.2, 186.9, 192.2, 194.4, 189.9, 179.1, 180.1, 178.7, 172.6, 179.3, 171.4, 164.7, 157.7, 157.0, 157.0, 152.0, 140.2, 148.0, 145.1, 148.2]}}
Tours
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [205.6, 203.4, 189.1, 187.3, 188.0, 194.1, 200.1, 202.1, 205.2, 215.7, 215.2, 215.5, 208.7, 196.9, 189.2, 188.4, 185.6, 188.3, 189.8, 185.4, 183.0, 187.7, 179.8, 178.8, 177.5, 177.1, 176.4, 173.8, 178.1, 185.7, 189.1]}}
Grenoble
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [206.7, 215.6, 212.5, 207.1, 206.2, 199.0, 199.4, 196.2, 198.3, 202.0, 202.7, 203.7, 206.6, 208.1, 200.1, 195.4, 190.3, 186.8, 185.5, 177.5, 174.4, 176.9, 174.1, 165.2, 160.9, 158.9, 153.0, 139.1, 130.5, 122.5, 126.8]}}
Saint Etienne
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [271.9, 274.4, 276.1, 275.4, 267.7, 263.0, 252.9, 246.7, 239.5, 240.5, 231.9, 232.7, 230.9, 225.1, 218.0, 220.8, 218.4, 221.8, 221.8, 208.5, 207.2, 202.0, 198.8, 189.5, 181.0, 181.5, 177.2, 178.7, 180.1, 169.2, 180.8]}}
Nantes
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [148.9, 147.0, 151.4, 155.5, 154.6, 148.5, 144.3, 147.2, 155.5, 152.9, 151.2, 151.9, 154.0, 151.9, 152.3, 142.4, 133.7, 130.2, 125.8, 111.4, 109.5, 107.4, 104.2, 103.7, 103.7, 103.8, 105.8, 105.8, 103.2, 107.6, 111.8]}}
Orléans
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [160.5, 163.4, 165.0, 156.8, 160.0, 159.6, 153.1, 155.8, 156.7, 153.0, 156.1, 156.0, 153.4, 152.1, 144.0, 137.1, 144.0, 149.1, 144.2, 129.9, 127.6, 129.8, 128.5, 116.4, 110.2, 113.0, 117.8, 114.4, 115.5, 124.1, 134.3]}}
Nancy
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [215.9, 217.0, 216.0, 232.0, 234.9, 253.1, 270.5, 287.9, 293.4, 287.8, 277.5, 276.6, 240.9, 224.1, 197.5, 181.9, 178.1, 177.9, 176.9, 178.2, 175.7, 180.8, 181.0, 180.9, 166.1, 166.6, 166.7, 159.5, 155.8, 166.0, 176.0]}}
Metz
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [268.1, 283.1, 288.2, 295.8, 298.9, 337.3, 357.4, 359.9, 365.2, 398.3, 396.0, 398.3, 374.6, 362.4, 370.0, 363.4, 347.1, 362.9, 363.1, 370.9, 369.6, 364.1, 366.2, 350.1, 349.8, 349.5, 353.1, 363.6, 385.5, 393.9, 399.9]}}
Lille
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [143.3, 143.5, 148.6, 151.1, 150.5, 148.6, 151.4, 154.9, 157.5, 164.2, 166.7, 167.9, 171.4, 169.8, 171.0, 174.5, 172.3, 175.3, 176.0, 175.0, 179.5, 182.8, 182.0, 181.8, 182.5, 182.8, 188.6, 194.4, 199.5, 209.1, 218.4]}}
Clermont-Auvergne
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [244.4, 256.0, 264.4, 267.2, 268.2, 260.9, 245.3, 237.9, 234.0, 222.6, 224.1, 221.9, 228.4, 229.6, 223.9, 210.5, 211.6, 203.6, 203.9, 189.5, 176.9, 172.4, 171.6, 161.3, 158.5, 159.3, 168.4, 172.7, 172.3, 170.3, 168.9]}}
Strasbourg
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [232.0, 236.6, 240.6, 241.6, 241.4, 249.4, 247.9, 252.6, 264.7, 272.0, 271.9, 271.9, 275.7, 270.5, 262.8, 245.0, 234.3, 228.2, 228.8, 214.7, 206.4, 199.2, 193.3, 187.5, 188.5, 185.9, 177.7, 180.7, 178.6, 182.7, 184.6]}}
Lyon
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [219.9, 223.3, 228.4, 228.4, 228.9, 234.4, 233.2, 234.2, 237.6, 238.1, 237.7, 237.9, 235.5, 237.1, 239.9, 236.6, 235.6, 240.5, 240.1, 235.8, 230.4, 221.5, 222.2, 218.5, 213.4, 213.4, 209.3, 212.0, 219.0, 219.6, 224.3]}}
Paris
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [212.4, 216.4, 221.0, 221.8, 221.2, 222.4, 224.3, 225.9, 228.9, 231.3, 234.7, 236.5, 242.8, 248.1, 249.6, 248.6, 249.5, 247.8, 246.8, 245.7, 245.7, 246.0, 245.3, 244.8, 244.8, 245.0, 247.7, 250.2, 258.2, 270.1, 282.0]}}
Rouen
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [161.0, 166.4, 168.9, 172.4, 170.2, 165.4, 160.5, 162.3, 159.0, 156.7, 156.1, 155.5, 155.0, 159.8, 155.5, 149.8, 151.4, 148.7, 146.9, 142.1, 139.8, 136.0, 134.7, 130.3, 129.5, 130.8, 135.8, 145.3, 159.6, 167.3, 181.5]}}
Toulon
{'incidence': {'jour_nom': 'jour_metropoles', 'valeur': [314.2, 333.7, 336.0, 345.4, 346.3, 348.0, 343.9, 335.3, 307.4, 303.2, 293.2, 291.4, 268.0, 264.3, 259.5, 252.3, 247.7, 245.7, 245.1, 235.1, 221.9, 208.6, 199.5, 191.8, 186.2, 186.3, 192.4, 186.1, 195.5, 196.2, 201.2]}}

In [128]:
dict_data = dataexplorer_age()

36it [03:29,  5.82s/it]

977