In [1]:
"""

LICENSE MIT
2020
Guillaume Rozier
Website : http://www.covidtracker.fr
Mail : guillaume.rozier@telecomnancy.net

README:
This file contains scripts that download data from data.gouv.fr and then process it to build many graphes.
I'm currently cleaning the code, please ask me if something is not clear enough.

The charts are exported to 'charts/images/france'.
Data is download to/imported from 'data/france'.
Requirements: please see the imports below (use pip3 to install them).

"""

"\n\nLICENSE MIT\n2020\nGuillaume Rozier\nWebsite : http://www.covidtracker.fr\nMail : guillaume.rozier@telecomnancy.net\n\nREADME:\nThis file contains scripts that download data from data.gouv.fr and then process it to build many graphes.\nI'm currently cleaning the code, please ask me if something is not clear enough.\n\nThe charts are exported to 'charts/images/france'.\nData is download to/imported from 'data/france'.\nRequirements: please see the imports below (use pip3 to install them).\n\n"

In [80]:
def nbWithSpaces(nb):
    str_nb = str(int(round(nb)))
    if(nb>100000):
        return str_nb[:3] + " " + str_nb[3:]
    elif(nb>10000):
        return str_nb[:2] + " " + str_nb[2:]
    elif(nb>1000):
        return str_nb[:1] + " " + str_nb[1:]
    else:
        return str_nb

In [12]:
import pandas as pd
PATH = "../../"
import france_data_management as data
import plotly.graph_objects as go

In [65]:
data.download_data()
df_tests =data.import_data_tests_sexe()
df_tests = df_tests[df_tests.cl_age90 == 0]
df_tests["P_rolling"] = df_tests["P"].rolling(window=7).mean()
df_tests

36it [00:03,  9.78it/s]

,fra,jour,P_f,P_h,P,T_f,T_h,T,cl_age90,pop,P_rolling
10,FR,2020-05-13,537,361,901,23368,16324,39872,0,67114995.0,NaN
21,FR,2020-05-14,561,418,1013,25327,17616,43188,0,67114995.0,NaN
32,FR,2020-05-15,565,447,1046,27514,20518,48470,0,67114995.0,NaN
43,FR,2020-05-16,160,131,292,9232,7342,16674,0,67114995.0,NaN
54,FR,2020-05-17,78,62,140,3446,3162,6642,0,67114995.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3222,FR,2021-03-01,16668,14958,31778,221179,187604,409761,0,67114995.0,21226.571429
3233,FR,2021-03-02,12896,11450,24506,187781,151828,340563,0,67114995.0,21058.571429
3244,FR,2021-03-03,12132,11193,23459,174513,147835,323318,0,67114995.0,20950.714286
3255,FR,2021-03-04,12241,11064,23435,186280,159297,346655,0,67114995.0,20844.571429
3266,FR,2021-03-05,12796,11719,24667,210154,182776,394751,0,67114995.0,20800.571429

In [3]:
data.download_data_variants()
df_variants = data.import_data_variants()
df_variants

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS
0,FR,2021-02-12-2021-02-18,9,3553,56.1,1890,53.2,143,4.0,375,10.6,1145,32.2
1,FR,2021-02-12-2021-02-18,19,10478,53.1,5323,50.8,497,4.7,868,8.3,3790,36.2
2,FR,2021-02-12-2021-02-18,29,11630,49.2,5656,48.6,592,5.1,968,8.3,4414,38.0
3,FR,2021-02-12-2021-02-18,39,12240,50.3,6237,51.0,548,4.5,977,8.0,4478,36.6
4,FR,2021-02-12-2021-02-18,49,12369,51.9,6202,50.1,506,4.1,965,7.8,4696,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,FR,2021-02-23-2021-03-01,0,103271,59.5,60877,58.9,5638,5.5,8452,8.2,28304,27.4
172,FR,2021-02-24-2021-03-02,0,102523,59.3,62194,60.7,5479,5.3,8341,8.1,26509,25.9
173,FR,2021-02-25-2021-03-03,0,101099,58.6,62861,62.2,5305,5.2,8226,8.1,24707,24.4
174,FR,2021-02-26-2021-03-04,0,97890,57.2,62202,63.5,5114,5.2,7903,8.1,22671,23.2
175,FR,2021-02-27-2021-03-05,0,89756,52.7,58080,64.7,4521,5.0,7311,8.1,19844,22.1

In [16]:
df_variants["jour"] = df_variants.semaine.apply(lambda x: x[11:]) 
df_variants = df_variants[df_variants.cl_age90==0]
df_variants

/Users/guillaumerozier/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,fra,semaine,cl_age90,Nb_tests_PCR_TA_crible,Prc_tests_PCR_TA_crible,Nb_susp_501Y_V1,Prc_susp_501Y_V1,Nb_susp_501Y_V2_3,Prc_susp_501Y_V2_3,Nb_susp_IND,Prc_susp_IND,Nb_susp_ABS,Prc_susp_ABS,jour
160,FR,2021-02-12-2021-02-18,0,81186,51.9,37910,46.7,3492,4.3,6976,8.6,32808,40.4,2021-02-18
161,FR,2021-02-13-2021-02-19,0,88472,55.1,41215,46.6,3980,4.5,7771,8.8,35506,40.1,2021-02-19
162,FR,2021-02-14-2021-02-20,0,91454,56.1,42905,46.9,4244,4.6,7939,8.7,36366,39.8,2021-02-20
163,FR,2021-02-15-2021-02-21,0,92168,56.4,43368,47.1,4265,4.6,8054,8.7,36481,39.6,2021-02-21
164,FR,2021-02-16-2021-02-22,0,96167,57.1,47266,49.1,4434,4.6,8460,8.8,36007,37.4,2021-02-22
165,FR,2021-02-17-2021-02-23,0,99237,57.8,50444,50.8,4767,4.8,8753,8.8,35273,35.5,2021-02-23
166,FR,2021-02-18-2021-02-24,0,101260,58.2,53328,52.7,4936,4.9,8693,8.6,34303,33.9,2021-02-24
167,FR,2021-02-19-2021-02-25,0,102583,58.7,55632,54.2,5061,4.9,8834,8.6,33056,32.2,2021-02-25
168,FR,2021-02-20-2021-02-26,0,103069,58.9,57562,55.8,5374,5.2,8651,8.4,31482,30.5,2021-02-26
169,FR,2021-02-21-2021-02-27,0,103362,59.0,58444,56.5,5525,5.3,8668,8.4,30725,29.7,2021-02-27
170,FR,2021-02-22-2021-02-28,0,103400,59.0,58603,56.7,5546,5.4,8637,8.4,30614,29.6,2021-02-28
171,FR,2021-02-23-2021-03-01,0,103271,59.5,60877,58.9,5638,5.5,8452,8.2,28304,27.4,2021-03-01
172,FR,2021-02-24-2021-03-02,0,102523,59.3,62194,60.7,5479,5.3,8341,8.1,26509,25.9,2021-03-02
173,FR,2021-02-25-2021-03-03,0,101099,58.6,62861,62.2,5305,5.2,8226,8.1,24707,24.4,2021-03-03
174,FR,2021-02-26-2021-03-04,0,97890,57.2,62202,63.5,5114,5.2,7903,8.1,22671,23.2,2021-03-04
175,FR,2021-02-27-2021-03-05,0,89756,52.7,58080,64.7,4521,5.0,7311,8.1,19844,22.1,2021-03-05

In [26]:
df_variants.Nb_tests_PCR_TA_crible / (df_variants.Prc_tests_PCR_TA_crible/100)

160    156427.745665
161    160566.243194
162    163019.607843
163    163418.439716
164    168418.563923
165    171690.311419
166    173986.254296
167    174758.091993
168    174989.813243
169    175189.830508
170    175254.237288
171    173564.705882
172    172888.701518
173    172523.890785
174    171136.363636
175    170314.990512
dtype: float64

In [87]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_ABS,
        name="% souche classique (" + str(df_variants.Prc_susp_ABS.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
        stackgroup='one'
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V1,
        name="% variant UK (" + str(df_variants.Prc_susp_501Y_V1.values[-1]).replace(".", ",") + " %)",
        stackgroup='one'
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_501Y_V2_3,
        name="% variants SA + BZ (" + str(df_variants.Prc_susp_501Y_V2_3.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
        stackgroup='one'
    )
)

fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=df_variants.Prc_susp_IND,
        name="% variants indéterminés (" + str(df_variants.Prc_susp_IND.values[-1]).replace(".", ",") + " %)",
        showlegend=True,
        stackgroup='one'
    )
)

fig.update_yaxes(ticksuffix="%")

fig.update_layout(
     title={
        'text': "Proportion de variants dans les tests positifs (en %)",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Date : 08/03/21. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.',
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_pourcent"), scale=2, width=1000, height=600)

In [86]:
fig = go.Figure()
n_days = len(df_variants)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V1.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variant UK </b><br>" + str(nbWithSpaces(y[-1])).replace(".", ",") + "",
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_501Y_V2_3.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variants SA + BZ </b><br>" + str(nbWithSpaces(y[-1])) + "",
        showlegend=True,
        stackgroup='one'
    )
)

y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_IND.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Variant indéterminé </b><br>" + str(nbWithSpaces(y[-1])) + "",
        showlegend=True,
        stackgroup='one'
    )
)
y=df_tests["P_rolling"].values[-n_days:] * df_variants.Prc_susp_ABS.values/100
fig.add_trace(
    go.Scatter(
        x=df_variants.jour,
        y=y,
        name="<b>Souche classique </b><br>" + str(nbWithSpaces(y[-1])) + "",
        showlegend=True,
        stackgroup='one'
    )
)

fig.update_yaxes(ticksuffix="")

fig.update_layout(
     title={
        'text': "Nombre de variants dans les cas détectés",
        'y':0.99,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top',
         'font': {'size': 30}
    },
    annotations = [
                    dict(
                        x=0.5,
                        y=1.1,
                        xref='paper',
                        yref='paper',
                        text='Date : 08/03/21. Données : Santé publique France. Auteur : @guillaumerozier - covidtracker.fr.',
                        showarrow = False
                    )]
)
fig.write_image(PATH+"images/charts/france/{}.jpeg".format("variants_nombre"), scale=2, width=1000, height=600)